# Generated by Django 4.0.4 on 2022-05-25 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=255)),
                ('album_title', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=200)),
                ('album_logo', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rock', models.CharField(max_length=255)),
                ('smooth', models.CharField(max_length=200)),
                ('instrumental', models.CharField(max_length=400)),
                ('soft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.album')),
            ],
        ),
    ]
