# Generated by Django 4.0.4 on 2022-05-27 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_product_contact_contact_email_contact_contact_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contact_email',
            new_name='details',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_name',
        ),
    ]
