# Generated by Django 4.0.4 on 2022-04-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.SmallIntegerField(default='0'),
            preserve_default=False,
        ),
    ]
