gender_dict = {"1" : "MALE", "2" : "FEMALE", "3" : "TRANSGENDER"}

print(gender_dict.get("1"))
print(gender_dict.get("2"))
print(gender_dict.get("3"))






indianstates_dict = {"01":"Jammu and Kashmir","02":"Himachal Pradesh","03":"Punjab","04":"Chandigarh","05":"Uttarakhand","06":"Haryana","07":"Delhi","08":"Rajasthan","09":"Uttar Pradesh", "10":"Bihar","11":"Sikkim","12":"Arunachal Pradesh","13":"Nagaland","14":"Manipur","15":"Mizoram","16":"Tripura","17":"Meghalaya","18":"Assam","19":"West Bengal","20":"Jharkhand","21":"Odisha","22":"Chhattisgarh","23":"Madhya Pradesh","24":"Gujarat","25":"Daman and Diu","26":"Dadra and Nagar Haveli","27":"Maharashtra","28":"Andhra Pradesh","29":"Karnataka","30":"Goa","31":"Lakshadweep","32":"Kerala","33":"TamilNadu","34":"Puducherry","35":"Andaman and Nicobar Islands","36":"Telangana"}
print(indianstates_dict.get("01"))
print(indianstates_dict.get("02"))
print(indianstates_dict.get("03"))
print(indianstates_dict.get("04"))
print(indianstates_dict.get("05"))
print(indianstates_dict.get("06"))
print(indianstates_dict.get("07"))
print(indianstates_dict.get("08"))
print(indianstates_dict.get("09"))
print(indianstates_dict.get("10"))
print(indianstates_dict.get("11"))
print(indianstates_dict.get("12"))
print(indianstates_dict.get("13"))
print(indianstates_dict.get("14"))
print(indianstates_dict.get("15"))
print(indianstates_dict.get("16"))
print(indianstates_dict.get("17"))
print(indianstates_dict.get("18"))
print(indianstates_dict.get("19"))
print(indianstates_dict.get("20"))
print(indianstates_dict.get("21"))
print(indianstates_dict.get("22"))
print(indianstates_dict.get("23"))
print(indianstates_dict.get("24"))
print(indianstates_dict.get("25"))
print(indianstates_dict.get("26"))
print(indianstates_dict.get("27"))
print(indianstates_dict.get("28"))
print(indianstates_dict.get("29"))
print(indianstates_dict.get("30"))
print(indianstates_dict.get("31"))
print(indianstates_dict.get("32"))
print(indianstates_dict.get("33"))
print(indianstates_dict.get("34"))
print(indianstates_dict.get("35"))
print(indianstates_dict.get("36"))





account_type_code_dict = {"1":"AUTO LOAN","2":"HOUSING LOAN","3":"PROPERTY LOAN","4":"LOAN AGAINST SHARES/SECURITIES","5":"PERSONAL LOAN","6":"CONSUMER LOAN","7":"GOLD LOAN","8":"EDUCATIONAL LOAN","9":"LOAN TO PROFESSIONAL", "10":"CREDIT CARD","11":"LEASING","12":"OVERDRAFT","13":"TWO-WHEELER LOAN","14":"NON-FUNDED CREDIT FACILITY","15":"LOAN AGAINST BANK DEPOSITS","16":"FLEET CARD","17":"Commercial Vehicle Loan","18":"Telco – Wireless","19":"Telco – Broadband","20":"Telco – Landline","23":"GECL Secured","24":"GECL Unsecured","31":"Secured Credit Card","32":"Used Car Loan","33":"Construction Equipment Loan","34":"Tractor Loan","35":"Corporate Credit Card","36":"Kisan Credit Card","37":"Loan on Credit Card","38":"Prime Minister Jaan Dhan Yojana - Overdraft","39":"Mudra Loans – Shishu / Kishor / Tarun","40":"Microfinance – Business Loan","41":"Microfinance – Personal Loan","42":"Microfinance – Housing Loan","43":"Microfinance – Others","44":"Pradhan Mantri Awas Yojana - Credit Link Subsidy Scheme MAY CLSS", "45" : "P2P Personal Loan", "46" : "P2P Auto Loan", "47" : "P2P Education Loan", "51" : "BUSINESS LOAN – GENERAL", "52" : "BUSINESS LOAN –PRIORITY SECTOR – SMALL BUSINESS", "53" : "BUSINESS LOAN –PRIORITY SECTOR – AGRICULTURE", "54" : "BUSINESS LOAN –PRIORITY SECTOR – OTHERS", "55" : "BUSINESS NON-FUNDED CREDIT FACILITY – GENERAL", "56" : "BUSINESS NON-FUNDED CREDIT FACILITY – PRIORITY SECTOR – SMALL BUSINESS", "57" : "BUSINESS NON-FUNDED CREDIT FACILITY – PRIORITY SECTOR – AGRICULTURE", "58" : "BUSINESS NON-FUNDED CREDIT FACILITY – PRIORITY SECTOR – OTHERS", "59" : "BUSINESS LOANS AGAINST BANK DEPOSITS", "60" : "Staff Loan", "61" : "Business Loan - Unsecured", "00" : "Others"}

print(account_type_code_dict.get("1"))
print(account_type_code_dict.get("2"))
print(account_type_code_dict.get("3"))
print(account_type_code_dict.get("4"))
print(account_type_code_dict.get("5"))
print(account_type_code_dict.get("6"))
print(account_type_code_dict.get("7"))
print(account_type_code_dict.get("8"))
print(account_type_code_dict.get("9"))
print(account_type_code_dict.get("10"))
print(account_type_code_dict.get("11"))
print(account_type_code_dict.get("12"))
print(account_type_code_dict.get("13"))
print(account_type_code_dict.get("14"))
print(account_type_code_dict.get("15"))
print(account_type_code_dict.get("16"))
print(account_type_code_dict.get("17"))
print(account_type_code_dict.get("18"))
print(account_type_code_dict.get("19"))
print(account_type_code_dict.get("20"))
print(account_type_code_dict.get("23"))
print(account_type_code_dict.get("24"))
print(account_type_code_dict.get("31"))
print(account_type_code_dict.get("32"))
print(account_type_code_dict.get("34"))
print(account_type_code_dict.get("35"))
print(account_type_code_dict.get("36"))
print(account_type_code_dict.get("37"))
print(account_type_code_dict.get("38"))
print(account_type_code_dict.get("39"))
print(account_type_code_dict.get("40"))
print(account_type_code_dict.get("41"))
print(account_type_code_dict.get("42"))
print(account_type_code_dict.get("43"))
print(account_type_code_dict.get("44"))
print(account_type_code_dict.get("45"))
print(account_type_code_dict.get("46")) 
print(account_type_code_dict.get("47"))
print(account_type_code_dict.get("51")) 
print(account_type_code_dict.get("52"))
print(account_type_code_dict.get("53"))
print(account_type_code_dict.get("54"))
print(account_type_code_dict.get("55")) 
print(account_type_code_dict.get("56"))
print(account_type_code_dict.get("57"))
print(account_type_code_dict.get("58"))
print(account_type_code_dict.get("59"))
print(account_type_code_dict.get("60"))
print(account_type_code_dict.get("61"))
print(account_type_code_dict.get("00"))




account_status_code = {"00" : "No Suit Filed", "89" : "Wilful default", "93" : "Suit Filed(Wilful default)", "97" : "Suit Filed(Wilful Default) and Written-off", "30" : "Restructured", "31" : "Restructured Loan (Govt. Mandated)", "32" : "Settled", "33" : "Post (WO) Settled", "34" : "Account Sold", "35" : "Written Off and Account Sold", "36" : "Account Purchased", "37" : "Account Purchased and Written Off", "38" : "Account Purchased and Settled", "39" : "Account Purchased and Restructured", "40" : "Status Cleared", "41" : "Restructured Loan", "42" : "Restructured Loan (Govt. Mandated)", "43" : "Written-off", "44" : "Settled", "45" : "Post (WO) Settled" , "46" : "Account Sold", "47" : "Written Off and Account Sold", "48" : "Account Purchased", "49" : "Account Purchased and Written Off", "50" : "Account Purchased and Settled", "51" : "Account Purchased and Restructured", "52" : "Status Cleared", "53" : "Suit Filed", "54" : "Suit Filed and Written-off", "55" : "Suit Filed and Settled", "56" : "Suit Filed and Post (WO) Settled", "57" : "Suit Filed and Account Sold", "58" : "Suit Filed and Written Off and Account Sold", "59" : "Suit Filed and Account Purchased", "60" : "Suit Filed and Account Purchased and Written Off", "61" : "Suit Filed and Account Purchased and Settled", "62" : "Suit Filed and Account Purchased and Restructured", "63" : "Suit Filed and Status Cleared", "64" : "Wilful Default and Restructured Loan", "65" : "Wilful Default and Restructured Loan (Govt. Mandated)", "66" : "Wilful Default and Settled", "67" : "Wilful Default and Post (WO) Settled", "68" : "Wilful Default and Account Sold", "69" : "Wilful Default and Written Off and Account Sold", "70" : "Wilful Default and Account Purchased", "72" : "Wilful Default and Account Purchased and Written Off", "73" : "Wilful Default and Account Purchased and Settled", "74" : "Wilful Default and Account Purchased and Restructured", "75" : "Wilful Default and Status Cleared", "76" : "Suit filed (Wilful default) and Restructured", "77" : "Suit filed (Wilful default) and Restructured Loan (Govt.Mandated)", "79" : "Suit filed (Wilful default) and Settled", "81" : "Suit filed (Wilful default) and Post (WO) Settled", "85" : "Suit filed (Wilful default) and Account Sold", "86" : "Suit filed (Wilful default) and Written Off and Account Sold", "87" : "Suit filed (Wilful default) and Account Purchased", "88" : "Suit filed (Wilful default) and Account Purchased and WrittenOff", "94" : "Suit filed (Wilful default) and Account Purchased and Settled", "90" : "Suit filed (Wilful default) and Account Purchased and Restructured", "91" : "Suit filed (Wilful default) and Status Cleared", "13" : "CLOSED", "14" : "CLOSED", "15" : "CLOSED", "16" : "CLOSED", "16" : "CLOSED", "16" : "CLOSED", "17" : "CLOSED", "12" : "CLOSED", "11" : "ACTIVE", "71" : "ACTIVE", "78" : "ACTIVE", "80" : "ACTIVE", "82" : "ACTIVE", "83" : "ACTIVE", "84" : "ACTIVE", "DEFAULTVALUE" : "ACTIVE", "21" : "ACTIVE", "22" : "ACTIVE", "23" : "ACTIVE", "24" : "ACTIVE", "25" : "ACTIVE", "131" : "Restructured due to natural calamity", "130" : "Restructured due to COVID-19"}

print(account_status_code.get("00"))
print(account_status_code.get("89"))
print(account_status_code.get("93"))
print(account_status_code.get("97"))
print(account_status_code.get("30"))
print(account_status_code.get("31"))
print(account_status_code.get("32"))
print(account_status_code.get("33"))
print(account_status_code.get("34"))
print(account_status_code.get("35"))
print(account_status_code.get("36"))
print(account_status_code.get("37"))
print(account_status_code.get("38"))
print(account_status_code.get("39"))
print(account_status_code.get("40"))
print(account_status_code.get("41"))
print(account_status_code.get("42"))
print(account_status_code.get("43"))
print(account_status_code.get("44"))
print(account_status_code.get("45"))
print(account_status_code.get("46"))
print(account_status_code.get("47"))
print(account_status_code.get("48"))
print(account_status_code.get("49"))
print(account_status_code.get("50"))
print(account_status_code.get("51"))
print(account_status_code.get("52"))
print(account_status_code.get("53"))
print(account_status_code.get("54"))
print(account_status_code.get("55"))
print(account_status_code.get("56"))
print(account_status_code.get("57"))
print(account_status_code.get("58"))
print(account_status_code.get("59"))
print(account_status_code.get("60"))
print(account_status_code.get("61"))
print(account_status_code.get("62")) 
print(account_status_code.get("63"))
print(account_status_code.get("64")) 
print(account_status_code.get("65"))
print(account_status_code.get("66"))
print(account_status_code.get("67"))
print(account_status_code.get("68")) 
print(account_status_code.get("69"))
print(account_status_code.get("70"))
print(account_status_code.get("72"))
print(account_status_code.get("73"))
print(account_status_code.get("74"))
print(account_status_code.get("75"))
print(account_status_code.get("76"))
print(account_status_code.get("77"))
print(account_status_code.get("79"))
print(account_status_code.get("81"))
print(account_status_code.get("85"))
print(account_status_code.get("86"))
print(account_status_code.get("87"))
print(account_status_code.get("88"))
print(account_status_code.get("94"))
print(account_status_code.get("90"))
print(account_status_code.get("91"))
print(account_status_code.get("13"))
print(account_status_code.get("14"))
print(account_status_code.get("15"))
print(account_status_code.get("16"))
print(account_status_code.get("16"))
print(account_status_code.get("16"))
print(account_status_code.get("17"))
print(account_status_code.get("12"))
print(account_status_code.get("11"))
print(account_status_code.get("71"))
print(account_status_code.get("78"))
print(account_status_code.get("80"))
print(account_status_code.get("82"))
print(account_status_code.get("83"))
print(account_status_code.get("84"))
print(account_status_code.get("DEFAULTVALUE"))
print(account_status_code.get("21"))
print(account_status_code.get("22"))
print(account_status_code.get("23"))
print(account_status_code.get("24"))
print(account_status_code.get("25"))
print(account_status_code.get("131"))
print(account_status_code.get("130"))




account_holder_type_code = {"1" : "Individual", "2" : "Joint", "3" : "Authorized User", "7" : "Guarantor", "20" : "Deceased"}

print(account_holder_type_code.get("1"))
print(account_holder_type_code.get("2"))
print(account_holder_type_code.get("3"))
print(account_holder_type_code.get("7"))
print(account_holder_type_code.get("20"))




employment_status_and_occupation_code = {"S" : "Salaried", "N" : "Non-Salaried", "E" : "Self-employed", "P" : "Self-employed Professional", "U" : "Unemployed"}

print(employment_status_and_occupation_code.get("S"))
print(employment_status_and_occupation_code.get("N"))
print(employment_status_and_occupation_code.get("E"))
print(employment_status_and_occupation_code.get("P"))
print(employment_status_and_occupation_code.get("U"))


marital_status_code = {"1" : "Single", "2" : "Married", "4" : "Divorced", "3" : "Widow/Widower"}

print(marital_status_code.get("1"))
print(marital_status_code.get("2"))
print(marital_status_code.get("4"))
print(marital_status_code.get("3"))




frequency_of_payments_code = {"D" : "Deferred", "P" : "Single payment loan", "W" : "Weekly", "B" : "Bi-Weekly", "E" : "Semi-monthly", "M" : "Monthly", "L" : "2 monthly (bimonthly)", "Q" : "3 monthly (quarterly)", "T" : "Triannualy", "S" : "Semiannually", "Y" : "Annually", "X" : "Variable", "U" : "Unknown"}

print(frequency_of_payments_code.get("D"))
print(frequency_of_payments_code.get("P"))
print(frequency_of_payments_code.get("W"))
print(frequency_of_payments_code.get("B"))
print(frequency_of_payments_code.get("E"))
print(frequency_of_payments_code.get("M"))
print(frequency_of_payments_code.get("Q"))
print(frequency_of_payments_code.get("T"))
print(frequency_of_payments_code.get("S"))
print(frequency_of_payments_code.get("Y"))
print(frequency_of_payments_code.get("X"))
print(frequency_of_payments_code.get("U"))




institution_type_code = {"PU" : "BANK", "PV" : "BANK", "FO" : "BANK", "RR" : "BANK", "CO" : "BANK", "NB" : "NBFC", "HF" : "HOUSING FINANCE COMPANY", "TE" : "TELECOM", "IN" : "INSURANCE", "MF" : "MICROFINANCE INSTITUTION", "CR" : "CREDIT RATING AGENCY"}

print(institution_type_code.get("PU"))
print(institution_type_code.get("PV"))
print(institution_type_code.get("FO"))
print(institution_type_code.get("RR"))
print(institution_type_code.get("CO"))
print(institution_type_code.get("NB"))
print(institution_type_code.get("HF"))
print(institution_type_code.get("TE"))
print(institution_type_code.get("IN"))
print(institution_type_code.get("MF"))
print(institution_type_code.get("CR"))