# Generated by Django 4.0.6 on 2022-07-19 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowExcel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video', models.CharField(max_length=100)),
                ('audio', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('language_id', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('USER_REVIEW', 'user_review'), ('EXPERT_REVIEW', 'expert_review'), ('OVERVIEW', 'overview')], max_length=30)),
                ('variant_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LikedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
