# Generated by Django 4.0.6 on 2022-07-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_showexcel_id_alter_showexcel_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
            ],
        ),
    ]
