# Generated by Django 4.0.6 on 2022-07-19 10:24

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0003_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutletQuoteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('l0', models.JSONField(null=True)),
                ('l1', models.JSONField(null=True)),
                ('l2', models.JSONField(null=True)),
                ('l3', models.JSONField(null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'outlet_quote_category',
            },
        ),
        migrations.DeleteModel(
            name='ContactInfo',
        ),
    ]
