# Generated by Django 4.0.4 on 2022-05-27 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0002_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geeksmodel',
            old_name='description',
            new_name='biography',
        ),
    ]
